# Generated by Django 5.1.7 on 2025-04-20 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentPerformanceAnalysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestion',
            name='options',
            field=models.CharField(default='select', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='subject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='StudentPerformanceAnalysis.subject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='assignmentresponse',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='assignment_responses/'),
        ),
        migrations.AlterField(
            model_name='test',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='correct_answer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='question_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testresponse',
            name='answers',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='testresponse',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
