# Generated by Django 5.1.7 on 2025-04-20 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentPerformanceAnalysis', '0002_testquestion_options_alter_assignment_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='StudentPerformanceAnalysis.subject'),
        ),
    ]
