# Generated by Django 5.1.7 on 2025-04-20 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentPerformanceAnalysis', '0004_alter_subject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='StudentPerformanceAnalysis.subject'),
        ),
    ]
