# Generated by Django 5.1.7 on 2025-04-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentPerformanceAnalysis', '0005_alter_test_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='assignmentresponse',
            name='file',
            field=models.FileField(upload_to='responses/'),
        ),
    ]
